# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://playinti.me
title: inTime
email: chris@playinti.me
author: Chris Hinstorff

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/play-in-time
  - title: try demo!
    url: http://playinti.me/app
  - title: use our api!
    url: https://docs.google.com/document/d/1dNrXyr32bGADFvmzc5DIDmI7emSev4aKCegbf4Sk_Dw