# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://playinti.me
title: inTime
email: chris@playinti.me
author: Chris Hinstorff
description: > # ""This app uses Spotify's music database (including song times 
and individual's genre preferences) to create a playlist that is 
perfectly-timed for any activity. That is, the playlist will end exactly at the
 end of the activity's duration."""

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/play-in-time
